import React from 'react';
import '../styles/globals.css';
import type { Metadata } from 'next';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Providers } from '@/providers';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
      </Head>
      <body>
        <Providers>
          {children}
          <ReactQueryDevtools
            initialIsOpen={false}
            panelProps={{ style: { background: '#094c79' } }}
          />
        </Providers>
      </body>
    </html>
  );
}
